project_name: TeleClaude

business:
  domains:
    software-development: docs

jobs:
  help_desk_intelligence:
    description: Agentic job to monitor support channels, summarize issues, and suggest fixes.
    schedule: daily
    preferred_hour: 6
    script: jobs/help_desk_intelligence.py
    agent: claude
    thinking_mode: fast

  youtube_scraper:
    description: Daily sync of YouTube subscriptions for content discovery and recommendation.
    schedule: daily
    preferred_hour: 6
    script: jobs/youtube_sync_subscriptions.py

  memory_review:
    schedule: weekly
    preferred_weekday: 0
    preferred_hour: 8
    type: agent
    job: memory-review
    agent: claude
    thinking_mode: fast

  log_bug_hunter:
    schedule: hourly
    type: agent
    job: log-bug-hunter
    agent: codex
    thinking_mode: fast
# git:
#   checkout_root: ~/Workspace/public-repos
