"""Parse and convert Claude/Gemini/Codex session transcripts to markdown."""

from teleclaude.utils.transcript._block_renderers import (
    _extract_tool_subject,
    _process_entry,
    _process_list_content,
    _process_string_content,
    _process_text_block,
    _process_thinking_block,
    _process_tool_result_block,
    _process_tool_use_block,
    _should_skip_entry,
    iter_assistant_blocks,
)
from teleclaude.utils.transcript._extraction import (
    _extract_last_message_by_role,
    _extract_text_from_content,
    _find_workdir_in_obj,
    collect_transcript_messages,
    count_renderable_assistant_blocks,
    extract_last_agent_message,
    extract_last_user_message,
    extract_last_user_message_with_timestamp,
    extract_recent_transcript_turns,
    extract_workdir_from_transcript,
    get_assistant_messages_since,
    parse_session_transcript,
)
from teleclaude.utils.transcript._iterators import (
    _entry_role,
    _get_entries_for_agent,
    _is_rotation_fallback_candidate,
    _iter_claude_entries,
    _iter_codex_entries,
    _iter_gemini_entries,
    _iter_jsonl_entries,
    _iter_jsonl_entries_tail,
    _start_index_after_timestamp_or_rotation,
)
from teleclaude.utils.transcript._parsers import (
    _extract_codex_reasoning_text,
    normalize_transcript_entry_message,
)
from teleclaude.utils.transcript._rendering import (
    AGENT_TRANSCRIPT_PARSERS,
    TranscriptParserInfo,
    _render_transcript_from_entries,
    get_transcript_parser_info,
    parse_claude_transcript,
    parse_codex_transcript,
    parse_gemini_transcript,
    render_agent_output,
    render_clean_agent_output,
)
from teleclaude.utils.transcript._tool_calls import (
    StructuredMessage,
    ToolCallRecord,
    TurnTimeline,
    _is_compaction_entry,
    _is_user_tool_result_only_message,
    _parse_function_call_arguments,
    extract_messages_from_chain,
    extract_structured_messages,
    extract_tool_calls_current_turn,
)
from teleclaude.utils.transcript._utils import (
    CHECKPOINT_JSONL_TAIL_ENTRIES,
    CHECKPOINT_JSONL_TAIL_READ_BYTES,
    _apply_tail_limit,
    _apply_tail_limit_codex,
    _escape_triple_backticks,
    _format_thinking,
    _format_timestamp_prefix,
    _italicize_thinking_line,
    _parse_timestamp,
    _wrap_thinking_emphasis,
)

__all__ = [
    # _rendering
    "AGENT_TRANSCRIPT_PARSERS",
    # _utils
    "CHECKPOINT_JSONL_TAIL_ENTRIES",
    "CHECKPOINT_JSONL_TAIL_READ_BYTES",
    # _tool_calls
    "StructuredMessage",
    "ToolCallRecord",
    "TranscriptParserInfo",
    "TurnTimeline",
    "_apply_tail_limit",
    "_apply_tail_limit_codex",
    # _iterators
    "_entry_role",
    "_escape_triple_backticks",
    # _parsers
    "_extract_codex_reasoning_text",
    # _extraction
    "_extract_last_message_by_role",
    "_extract_text_from_content",
    # _block_renderers
    "_extract_tool_subject",
    "_find_workdir_in_obj",
    "_format_thinking",
    "_format_timestamp_prefix",
    "_get_entries_for_agent",
    "_is_compaction_entry",
    "_is_rotation_fallback_candidate",
    "_is_user_tool_result_only_message",
    "_italicize_thinking_line",
    "_iter_claude_entries",
    "_iter_codex_entries",
    "_iter_gemini_entries",
    "_iter_jsonl_entries",
    "_iter_jsonl_entries_tail",
    "_parse_function_call_arguments",
    "_parse_timestamp",
    "_process_entry",
    "_process_list_content",
    "_process_string_content",
    "_process_text_block",
    "_process_thinking_block",
    "_process_tool_result_block",
    "_process_tool_use_block",
    "_render_transcript_from_entries",
    "_should_skip_entry",
    "_start_index_after_timestamp_or_rotation",
    "_wrap_thinking_emphasis",
    "collect_transcript_messages",
    "count_renderable_assistant_blocks",
    "extract_last_agent_message",
    "extract_last_user_message",
    "extract_last_user_message_with_timestamp",
    "extract_messages_from_chain",
    "extract_recent_transcript_turns",
    "extract_structured_messages",
    "extract_tool_calls_current_turn",
    "extract_workdir_from_transcript",
    "get_assistant_messages_since",
    "get_transcript_parser_info",
    "iter_assistant_blocks",
    "normalize_transcript_entry_message",
    "parse_claude_transcript",
    "parse_codex_transcript",
    "parse_gemini_transcript",
    "parse_session_transcript",
    "render_agent_output",
    "render_clean_agent_output",
]
