"""Tmux bridge for TeleClaude - handles tmux session management.

All functions are stateless and use config imported from teleclaude.config.
"""

from teleclaude.core.tmux_bridge._keys import (
    pid_is_alive,
    send_arrow_key,
    send_backspace,
    send_ctrl_key,
    send_enter,
    send_escape,
    send_keys,
    send_keys_existing_tmux,
    send_keys_to_tty,
    send_shift_tab,
    send_signal,
    send_tab,
)
from teleclaude.core.tmux_bridge._pane import (
    capture_pane,
    get_current_command,
    get_current_directory,
    get_pane_pid,
    get_pane_title,
    get_pane_tty,
    get_session_pane_id,
    is_pane_dead,
    is_process_running,
    kill_session,
    list_tmux_sessions,
    session_exists,
    start_pipe_pane,
    stop_pipe_pane,
    wait_for_shell_ready,
)
from teleclaude.core.tmux_bridge._session import (
    ensure_tmux_session,
    update_tmux_session,
)
from teleclaude.core.tmux_bridge._subprocess import (
    SUBPROCESS_TIMEOUT_DEFAULT,
    SUBPROCESS_TIMEOUT_LONG,
    SUBPROCESS_TIMEOUT_QUICK,
    SubprocessTimeoutError,
    communicate_with_timeout,
    wait_with_timeout,
)

__all__ = [
    "SUBPROCESS_TIMEOUT_DEFAULT",
    "SUBPROCESS_TIMEOUT_LONG",
    "SUBPROCESS_TIMEOUT_QUICK",
    "SubprocessTimeoutError",
    "capture_pane",
    "communicate_with_timeout",
    "ensure_tmux_session",
    "get_current_command",
    "get_current_directory",
    "get_pane_pid",
    "get_pane_title",
    "get_pane_tty",
    "get_session_pane_id",
    "is_pane_dead",
    "is_process_running",
    "kill_session",
    "list_tmux_sessions",
    "pid_is_alive",
    "send_arrow_key",
    "send_backspace",
    "send_ctrl_key",
    "send_enter",
    "send_escape",
    "send_keys",
    "send_keys_existing_tmux",
    "send_keys_to_tty",
    "send_shift_tab",
    "send_signal",
    "send_tab",
    "session_exists",
    "start_pipe_pane",
    "stop_pipe_pane",
    "update_tmux_session",
    "wait_for_shell_ready",
    "wait_with_timeout",
]
