"""Integration event model package."""

from teleclaude.core.integration.authorization import (
    CutoverResolution,
    IntegrationAuthorizationError,
    IntegratorCutoverControls,
    require_integrator_owner,
    resolve_cutover_mode,
)
from teleclaude.core.integration.blocked_followup import (
    BlockedFollowUpError,
    BlockedFollowUpLink,
    BlockedFollowUpStore,
)
from teleclaude.core.integration.event_store import AppendResult, IntegrationEventStore, IntegrationEventStoreError
from teleclaude.core.integration.events import (
    BranchPushedPayload,
    FinalizeReadyPayload,
    IntegrationBlockedPayload,
    IntegrationEvent,
    IntegrationEventPayload,
    IntegrationEventType,
    IntegrationEventValidationError,
    ReviewApprovedPayload,
    build_integration_event,
    compute_idempotency_key,
    parse_event_type,
    validate_event_payload,
)
from teleclaude.core.integration.lease import (
    IntegrationLeaseError,
    IntegrationLeaseStore,
    LeaseAcquireResult,
    LeaseAcquireStatus,
    LeaseRecord,
    LeaseRenewResult,
    LeaseRenewStatus,
)
from teleclaude.core.integration.queue import (
    IntegrationQueue,
    IntegrationQueueError,
    QueueItem,
    QueueStatus,
    QueueTransition,
)
from teleclaude.core.integration.readiness_projection import (
    CandidateKey,
    CandidateReadiness,
    IntegratedChecker,
    ProjectionUpdate,
    ReachabilityChecker,
    ReadinessProjection,
    ReadinessStatus,
)
from teleclaude.core.integration.runtime import (
    IntegrationBlockedOutcome,
    IntegrationRuntimeError,
    IntegratorShadowRuntime,
    MainBranchClearanceCheck,
    MainBranchClearanceProbe,
    ResumeBlockedResult,
    RuntimeDrainResult,
    SessionSnapshot,
    ShadowOutcome,
    ShadowOutcomeType,
    classify_standalone_sessions,
    tail_indicates_active_main_modification,
)
from teleclaude.core.integration.service import IngestionResult, IngestionStatus, IntegrationEventService

__all__ = [
    "AppendResult",
    "BlockedFollowUpError",
    "BlockedFollowUpLink",
    "BlockedFollowUpStore",
    "BranchPushedPayload",
    "CandidateKey",
    "CandidateReadiness",
    "CutoverResolution",
    "FinalizeReadyPayload",
    "IngestionResult",
    "IngestionStatus",
    "IntegratedChecker",
    "IntegrationAuthorizationError",
    "IntegrationBlockedOutcome",
    "IntegrationBlockedPayload",
    "IntegrationEvent",
    "IntegrationEventPayload",
    "IntegrationEventService",
    "IntegrationEventStore",
    "IntegrationEventStoreError",
    "IntegrationEventType",
    "IntegrationEventValidationError",
    "IntegrationLeaseError",
    "IntegrationLeaseStore",
    "IntegrationQueue",
    "IntegrationQueueError",
    "IntegrationRuntimeError",
    "IntegratorCutoverControls",
    "IntegratorShadowRuntime",
    "LeaseAcquireResult",
    "LeaseAcquireStatus",
    "LeaseRecord",
    "LeaseRenewResult",
    "LeaseRenewStatus",
    "MainBranchClearanceCheck",
    "MainBranchClearanceProbe",
    "ProjectionUpdate",
    "QueueItem",
    "QueueStatus",
    "QueueTransition",
    "ReachabilityChecker",
    "ReadinessProjection",
    "ReadinessStatus",
    "ResumeBlockedResult",
    "ReviewApprovedPayload",
    "RuntimeDrainResult",
    "SessionSnapshot",
    "ShadowOutcome",
    "ShadowOutcomeType",
    "build_integration_event",
    "classify_standalone_sessions",
    "compute_idempotency_key",
    "parse_event_type",
    "require_integrator_owner",
    "resolve_cutover_mode",
    "tail_indicates_active_main_modification",
    "validate_event_payload",
]
